# Form implementation generated from reading ui file 'c:\Users\omar\Documents\My TPs\LIA-TP\TP1\postfix.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(828, 583)
        MainWindow.setStyleSheet(".QPushButton{\n"
"color:#fff;\n"
"    \n"
"    font: 18pt \"Arial Black\";\n"
"    background-color: rgb(167, 144, 28);\n"
"border-radius:5px;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"  border: 2px solid #000;\n"
"  padding: 10px 20px;\n"
"\n"
"}\n"
"\n"
"@keyframes pulse {\n"
"  0% {\n"
"    transform: scale(1);\n"
"  }\n"
"  50% {\n"
"    transform: scale(1.2);\n"
"  }\n"
"  100% {\n"
"    transform: scale(1);\n"
"  }\n"
"\n"
"\n"
"}\n"
"QLabel{\n"
"font: 87 48pt \"Arial Black\";\n"
"text-decoration: underline;\n"
"color: rgb(162, 139, 46);\n"
"text-align: center;}\n"
"\n"
".QMainWindow{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
".QLineEdit{\n"
"\n"
"border-radius:5px;\n"
"font: 87 16pt \"Arial Black\";\n"
"color: rgb(152, 130, 19);\n"
" border-style: solid ;\n"
"   border-color: rgb(178, 132, 16);\n"
"   border-width: 5px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("margin:5px;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.input_screen = QtWidgets.QLineEdit(self.centralwidget)
        self.input_screen.setEnabled(False)
        self.input_screen.setMaximumSize(QtCore.QSize(16777206, 16777215))
        self.input_screen.setStyleSheet("fontsize:24pt;")
        self.input_screen.setObjectName("input_screen")
        self.verticalLayout.addWidget(self.input_screen)
        self.Postfix_screen = QtWidgets.QLineEdit(self.centralwidget)
        self.Postfix_screen.setEnabled(False)
        self.Postfix_screen.setMaximumSize(QtCore.QSize(16777206, 16777215))
        self.Postfix_screen.setStyleSheet("")
        self.Postfix_screen.setObjectName("Postfix_screen")
        self.verticalLayout.addWidget(self.Postfix_screen)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.compile = QtWidgets.QPushButton(self.centralwidget)
        self.compile.setObjectName("compile")
        self.gridLayout_2.addWidget(self.compile, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.validat = QtWidgets.QPushButton(self.centralwidget)
        self.validat.setObjectName("validat")
        self.gridLayout_2.addWidget(self.validat, 0, 2, 1, 1)
        self.drow = QtWidgets.QPushButton(self.centralwidget)
        self.drow.setObjectName("drow")
        self.gridLayout_2.addWidget(self.drow, 0, 1, 1, 1)
        self.dell = QtWidgets.QPushButton(self.centralwidget)
        self.dell.setObjectName("dell")
        self.gridLayout_2.addWidget(self.dell, 0, 3, 1, 1)
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setObjectName("clear")
        self.gridLayout_2.addWidget(self.clear, 0, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 3, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setStyleSheet("font: 18pt \"Impact\";")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 0, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 1, 3, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 1, 2, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 3, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 1, 1, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 3, 3, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 3, 4, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 3, 2, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setStyleSheet("font: 18pt \"Impact\";")
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout.addWidget(self.pushButton_17, 0, 4, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 4, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setStyleSheet("font: 18pt \"Impact\";")
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout.addWidget(self.pushButton_20, 0, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 1, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setStyleSheet("font: 18pt \"Impact\";")
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 0, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 4, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_18.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_18, 2, 2, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 2, 3, 1, 1)
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setStyleSheet("font: 18pt \"Impact\";")
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">TP - LIA Mohadi Amar</p></body></html>"))
        self.input_screen.setPlaceholderText(_translate("MainWindow", "Your Expression"))
        self.Postfix_screen.setPlaceholderText(_translate("MainWindow", "Postfix "))
        self.compile.setText(_translate("MainWindow", "compile"))
        self.validat.setText(_translate("MainWindow", "Validation"))
        self.drow.setText(_translate("MainWindow", "Drow"))
        self.dell.setText(_translate("MainWindow", "Dell"))
        self.clear.setText(_translate("MainWindow", "clear"))
        self.pushButton_13.setText(_translate("MainWindow", "k"))
        self.pushButton_11.setText(_translate("MainWindow", "↔"))
        self.pushButton_7.setText(_translate("MainWindow", "("))
        self.pushButton_10.setText(_translate("MainWindow", "q"))
        self.pushButton_19.setText(_translate("MainWindow", "n"))
        self.pushButton_8.setText(_translate("MainWindow", "p"))
        self.pushButton_16.setText(_translate("MainWindow", "s"))
        self.pushButton_15.setText(_translate("MainWindow", "z"))
        self.pushButton_12.setText(_translate("MainWindow", "w"))
        self.pushButton_17.setText(_translate("MainWindow", "¬"))
        self.pushButton_6.setText(_translate("MainWindow", ")"))
        self.pushButton_20.setText(_translate("MainWindow", "∪"))
        self.pushButton_4.setText(_translate("MainWindow", "d"))
        self.pushButton_9.setText(_translate("MainWindow", "g"))
        self.pushButton_14.setText(_translate("MainWindow", "→"))
        self.pushButton_3.setText(_translate("MainWindow", "c"))
        self.pushButton_2.setText(_translate("MainWindow", "b"))
        self.pushButton_18.setText(_translate("MainWindow", "a"))
        self.pushButton_5.setText(_translate("MainWindow", "e"))
        self.pushButton_1.setText(_translate("MainWindow", "∩"))
